### ISSUE TITLE
ArgumentException: The namespace declaration attribute has an incorrect 'namespaceURI': 'http://www.w3.org/2000/xmlns/'.

### ISSUE THREAD

**Issue by aaronvdbrugge** [universal-tools/UTNotificationsFeedback#100]
![image](https://user-images.githubusercontent.com/45329627/52706893-b62c7200-2f86-11e9-9a69-7a22f8838a1c.png)

I just downloaded this asset and I am getting this error. What can I do about it?

Also, my project has its own AndroidManifest.xml because I'm combining some features such as PlayFab, Facebook, camera availability, etc.

I see the asset has several AndroidManifests of its own and I'm wondering which one I'm supposed to combine with my own AndroidManifest?

Thank you.

**Comment by yuriy-universal-ivanov** [comment]
Hi @aaronvdbrugge ,

The issue you're describing is due to a bug in the implementation of System.Xml API in some versions of Unity. Fortunately, it's very easy to fix: just add the following attribute in the root <manifest> node of your Assets/Plugins/Android/AndroidManifest.xml:
  xmlns:amazon="http://schemas.amazon.com/apk/res/android"
f.e. it might look like 
  `<manifest xmlns:android="http://schemas.android.com/apk/res/android" package="com.unity3d.player" xmlns:tools="http://schemas.android.com/tools" android:installLocation="preferExternal" android:versionCode="1" android:versionName="1.0" xmlns:amazon="http://schemas.amazon.com/apk/res/android">`
after that.

Please let me know if you still need any assistance.

Best regards,
Yuriy, Universal Tools team.
