### ISSUE TITLE
Api Integration in Unity Project For Push Notification

### ISSUE THREAD

**Issue by MohitShivhare299** [universal-tools/UTNotificationsFeedback#121]
Hello,
I am new to push notification and having problem in integrating an api for push notification .
I already read ur documentation about UT Notification and cannot find any way to integrate api for sending remote notification. So if u can provide any documentation or video of how to send and recieve push notification using my server it will be very helpful.

**Comment by yuriy-universal-ivanov** [comment]
Hi @MohitShivhare299 ,

First of all, thank you for using our asset.

As your question is not actually an issue, but rather a technical support request, I suggest you to write to universal.tools.contact@gmail.com instead. Please also provide more details in that email: what part of the process described in the section "Push Notifications Overview" you struggle with, what you've already tried doing and where you've stuck.

I'll be happy to help you by email, and closing this issue here.

Best regards,
Yuriy, Universal Tools team.
