### ISSUE TITLE
Error with GooglePlayGamesPlugin-0.9.35.unitypackage

### ISSUE THREAD

**Issue by jun496** [universal-tools/UTNotificationsFeedback#33]
Hi, This is Jun.

I updated your asset to 1.6.1.1 and got problems with GooglePlayGamesPlugin-0.9.35.unitypackage.

Please let me know how do I use your UTNotification asset and GooglePlayGamesPlugin together.

Thanks,
Jun

**Comment by yuriy-universal-ivanov** [comment]
Hi @jun496 ,

Thanks for reporting about this issue. It took a while for us to figure out what's going wrong with Google Play Services plugin. The issue is caused by (it seems to be) a bug in Unity assets importer: it misdetects our plugin's file **Assets/UTNotifications/Editor/Android/UTNotificationsDependencies.cs** to be an updated version of GooglePlayGamesPlugin's **Assets/GooglePlayGames/Editor/GPGSDependencies.cs** when it is present in the project and replaces it, which is, of course, wrong.

You'll have to avoid this "smart" merging manually:
1. Revert the project to a version before importing a new version of UTNotifications.
2. Create a new empty Unity project, f.e. with a name utn_import.
3. Import the latest UTNotifications there.
4. Close Unity. Copy the folder Assets of utn_import.
5. Paste over your main project's Assets folder with merge (replacing any existing files).

It should work fine after that: both Assets/GooglePlayGames/Editor/GPGSDependencies.cs and Assets/UTNotifications/Editor/Android/UTNotificationsDependencies.cs are there. It helped it my case.

Please let me know about any difficulties, I'll be happy to help.

Best regards,
Yuriy, Universal Tools team.

**Comment by yuriy-universal-ivanov** [comment]
Hi @jun496,

May I already close the ticket?

Thanks.

Best regards,
Yuriy, Universal Tools team.

**Comment by jun496** [comment]
Of course.

Thanks.

Jun

2016년 11월 18일 (금) 오전 6:50, yuriy-universal-ivanov notifications@github.com님이
작성:
