### ISSUE TITLE
Google.JarResolver errors

### ISSUE THREAD

**Issue by Xaverix** [universal-tools/UTNotificationsFeedback#55]
Hi. I bought UTNotifications yesterday and today i tried to implement this plugin in my game, but in console i have errors :/ I tried downloading newer version of PlayServicesResolver but this gived me different errors. Here's screenshot (clean version, i have just imported it):

![screenshot_134](https://cloud.githubusercontent.com/assets/3581374/25774116/cfabbbe2-3289-11e7-8ba1-8c0e8993f912.png)

I have newest version of Android Support Library and Repository.

**Comment by yuriy-universal-ivanov** [comment]
Hi @Xaverix ,

First of all, thank you for purchasing UTNotifications!

Indeed, due to recent changes in Android SDK, Google Play Services Resolver got unable to resolve Android Support Library. Google has released an update fixing that issue: https://github.com/googlesamples/unity-jar-resolver/issues/47. This asset, though, introduces a new (rather minor) issue: https://github.com/googlesamples/unity-jar-resolver/issues/48. We created a patched version of the latest Play Services Resolver to fix it. You can download it here: https://drive.google.com/file/d/0B_4f5H4YL29eNUl3Y1dOaC1QNVk/view?usp=sharing.

We're going to submit a hotfix into Unity Asset Store now.

Feel free to contact us here or by email in case of any issues.

Best regards,
Yuriy, Universal Tools team.

**Comment by Xaverix** [comment]
Hi :)

Thanks a lot! Now i don't have any errors, but now i have another problem, i made everything step by step as it is in manual and my local notifications won't work :/ I made a script that displays console log in-game and in editor i can see message: "UTNotifications: not supported on this platform" but on android log is clear and notifications won't show up :/ (Tested PostLocalNotification and ScheduleNotification, In settings "Show Notifications" is set to "ALWAYS") Can you help me?

**Comment by yuriy-universal-ivanov** [comment]
Could you please send me a list of all files and folders in your Assets/Plugins/Android folder and a screenshot of UTNotifications settings in Unity?
Did you try UTNotifications sample scene to test local/scheduled notifications functionality or your own code? If your own code, please make sure you called UTNotifications.Manager.Instance.Initialize before using local and scheduled notifications API. Also, in that case please send me a piece of code where you're working with UTNotifications API.

**Comment by Xaverix** [comment]
Hello. Sorry. I fixed this problem. In my script I have used custom notification profile which i later deleted to re-import plugin. I changed it back to default and now everything works great!
