### ISSUE TITLE
App Icon not displayed on Android

### ISSUE THREAD

**Issue by SankaCoffee** [universal-tools/UTNotificationsFeedback#7]
The icon for the notifications is not displayed correct on Android. We use a (transparent) PNG file as icon. On some devices the icon is just a white square, on other devices the icon is displayed very small inside a square. I'm thinking it might be because of the transparency used in the icon.

Tested on 2 android devices:
- Nexus 4 with Android 5.1.1
- LG G3 with Android 5.0

The APK contains the app-icon in res/drawable/app_icon (a transparent PNG file)

**Comment by yuriy-universal-ivanov** [comment]
So, in brief the issue is described well here: http://stackoverflow.com/questions/28387602/notification-bar-icon-turns-white-in-android-5-lollipop (so it is Android 5+ only issue).
You have two options to solve it.
1. You can use icon with only two values of alpha: 0 or 1. Not transparent pixels then will be shown as white color and transparent one will be transparent. It is Android 5 default behaviour.
2. Add the following line to the Android manifest (Assets/Plugins/Android/AndroidManifest.xml):
<uses-sdk android:minSdkVersion="9" android:targetSdkVersion="20"/>
It should be a child of a root node <manifest>, you can add it right after that node. It will disable all the Android 5 features, but enables Android 4.4 compatibility for any Android 5+ devices. So the notification icons start looking as supposed to.
