### ISSUE TITLE
Android 8 Colour

### ISSUE THREAD

**Issue by vtimejc** [universal-tools/UTNotificationsFeedback#78]
Hi,

On my Oreo device (S8), notification icons become coloured when the notification area is dragged down.

How do I achieve this? I notice that androidIconBGColor is tagged as Android 5-7 only.

**Comment by yuriy-universal-ivanov** [comment]
Hi @vtimejc ,

Is it possible that you attach screenshot of what exactly you're talking about?

**Comment by vtimejc** [comment]
Hi @yuriy-universal-ivanov,

Here's a thread with some images that illustrate what I am talking about: https://stackoverflow.com/questions/45874742/android-color-notification-icon

(on my app, the icon is always white, even though I have set androidIconBGColor)

**Comment by yuriy-universal-ivanov** [comment]
Before Android API 26 (8.0), [setColor](https://developer.android.com/reference/android/app/Notification.Builder.html#setColor(int)) was used to specify a small icon background, but since 8.0 its behavior has changed - you can't specify the small icon background. See https://developer.android.com/reference/android/app/Notification.Builder.html#setColorized(boolean).

Android 8 chooses a suitable contrast color for a notification icon, so it's easily seen against each background (the color is different depending on the current background).

![image](https://user-images.githubusercontent.com/6696123/38953977-4be09c6c-4348-11e8-92ab-c0b30acffc6d.png)
![image](https://user-images.githubusercontent.com/6696123/38953982-55010296-4348-11e8-90f5-fd238e638d76.png)
![image](https://user-images.githubusercontent.com/6696123/38954001-65e88b88-4348-11e8-875b-5320be9e4856.png)

If you really want to specify the color, you might use [setColorized](https://developer.android.com/reference/android/app/Notification.Builder.html#setColorized(boolean)) on Android 8 (you'll have to modify the UTNotifications native plugin).

**Comment by vtimejc** [comment]
Hmm, odd. Do you know how it decides the automatic colour? e.g.

![2018-04-18 22 16 55_3](https://user-images.githubusercontent.com/32296827/38959067-0f1f391e-4357-11e8-98fc-4ab52e84dd2b.jpg)

**Comment by yuriy-universal-ivanov** [comment]
Hi @vtimejc,

Be default it's gray on a light background and white on a dark. You can specify a custom color with setColorized on Android O+. Please write me to universal.tools.contact@gmail.com and I'll send you a patch enabling using the color specified in the notification profile settings in the Android O+ titles.

**Comment by vtimejc** [comment]
Thanks for all your help!
